BooksRental/Controllers/DobleModelController.cs
using BooksRental.Models;
using BooksRental.POCOs;
using BooksRental.Repositories;
using System.Collections.Generic;
using System.Web.Mvc;

namespace BooksRental.Controllers
{
    public class DobleModelController : Controller
    {
        private AccountRepository AcRepo = new AccountRepository(GlobalVariables.ConnectionString);
        private BookGenderRepository BGRepo = new BookGenderRepository(GlobalVariables.ConnectionString);

        // GET: DobleModel
        public ActionResult Index()
        {
            ViewData["AccountTypes"] = AcRepo.GetAccountTypes();
            ViewData["BookGenders"] = BGRepo.GetAll();

            return View();
        }

        public ActionResult AjaxModel()
        {
            return View();
        }

        [HttpPost]
        public JsonResult getMyAccountTypes()
        {

            var AccountTypes = AcRepo.GetAccountTypes();
            List<AccountTypePOCO> listPoco = new List<AccountTypePOCO>();
            foreach (AccountType AT in AccountTypes)
            {
                AccountTypePOCO pocoObj = new AccountTypePOCO();
                pocoObj.AccountTypeId = AT.AccountTypeId;
                pocoObj.Name = AT.Name;

                listPoco.Add(pocoObj);
            }
            return Json(listPoco, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult getMyBookGenders()
        {
            var BookGenders = BGRepo.GetAll();
            List<BookGenderMetaData> listPoco = new List<BookGenderMetaData>();
            foreach (BookGender BG in BookGenders)
            {
                BookGenderMetaData pocoObj = new BookGenderMetaData();
                pocoObj.BookGenderId = BG.BookGenderId;
                pocoObj.Name = BG.Name;

                listPoco.Add(pocoObj);
            }
            return Json(listPoco, JsonRequestBehavior.AllowGet);
        }

    }
}

BooksRental/Views/DobleModel/AjaxModel.cshtml
@{
    ViewBag.Title = "Model Ajax Ex";
}

<script>
    $(document).ready(function () {
        //Account Type Data Table
        $tableAT = $('#dtAccountType').DataTable({
            responsive: true,
            "bPaginate": false,
            "bFilter": false,
            "bSort": false
        });

        //Book Gender Data Table
        $tableBG = $('#dtBookGender').DataTable({
            responsive: true,
            "bPaginate": false,
            "bFilter": false,
            "bSort": false
        });
        
        //We call the global modal
        $("#btnMoblal").on("click", function (e) {
            $.post('@Url.Action("Moblal", "GlobalModal")', { PageCalled: "@ViewBag.Title" }, function (data) {
                $('#contentRow').empty();
                $('#contentRow').append(data);
            })
        })

        getMyATData();
        getMyBGData();
    });

    function getMyATData() {
        $.ajax({
            type: "POST",
            url: "@Url.Action("getMyAccountTypes", "DobleModel")",
            data: JSON.stringify({
            }),
            dataType: "json",
            contentType: 'application/json; charset=utf-8',
            success: function (data) {
                $.each(data, function (i, obj) {
                    $tableAT.row.add([
                    obj.AccountTypeId,
                    obj.Name]).draw();
                })

            },
            error: function () {
                alert('ERRORRRR ! ! ! ! !  D:!');
            }
        });
    }

    function getMyBGData() {
        $.ajax({
            type: "POST",
            url: "@Url.Action("getMyBookGenders", "DobleModel")",
            data: JSON.stringify({
            }),
        dataType: "json",
        contentType: 'application/json; charset=utf-8',
        success: function (data) {
            $.each(data, function (i, obj) {
                $tableBG.row.add([
                obj.BookGenderId,
                obj.Name]).draw();
            })

        },
        error: function () {
            alert('ERRORRRR ! ! ! ! !  D:!');
        }
    });
    }
</script>

<div style="margin-top:10px">
    <button id="btnMoblal">Show Global Modal</button>
</div>

<div id="contentRow"></div>

<div class="row">
    <!-- Account Type Table -->
    <div class="col-md-6">
        <h2>
            Account Types
        </h2>
        <table id="dtAccountType" class="table">
            <thead>
                <tr>
                    <th>Account Type Id</th>
                    <th>Name of AT</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </div>

    <!-- Book Genders Table -->
    <div class="col-md-6">
        <h2>
            Book Genders
        </h2>
        <table id="dtBookGender" class="table">
            <thead>
                <tr>
                    <th>Book Gender Id</th>
                    <th>Name of BG</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

BooksRental/Views/DobleModel/Index.cshtml
@{
    ViewBag.Title = "Doble Model Ex";
}

<script>
    $(document).ready(function () {
        $("#btnMoblal").on("click", function (e) {
            $.post('@Url.Action("Moblal", "GlobalModal")', { PageCalled: "@ViewBag.Title" }, function (data) {
                $('#contentRow').empty();
                $('#contentRow').append(data);
            })
        })
    })
</script>

<div style="margin-top:10px">
    <button id="btnMoblal">Show Global Modal</button>
</div>

<div id="contentRow" ></div>

<div class="row">
    <!-- Account Type Table -->
    <div class="col-md-6">
        <h2>
            Account Types
        </h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Account Type Id</th>
                    <th>Name of AT</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewData["AccountTypes"] as IEnumerable<BooksRental.Models.AccountType>)
                {
                <tr>
                    <td>@item.AccountTypeId</td>
                    <td>@item.Name</td>
                </tr>
                }
            </tbody>
        </table>
    </div>

    <!-- Book Genders Table -->
    <div class="col-md-6">
        <h2>
            Book Genders
        </h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Book Gender Id</th>
                    <th>Name of BG</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewData["BookGenders"] as IEnumerable<BooksRental.Models.BookGender>)
                {
                    <tr>
                        <td>@item.BookGenderId</td>
                        <td>@item.Name</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>